### ISSUE TITLE
Change styling for links in titles

### ISSUE THREAD

**Issue by BobDotCom** [Pycord-Development/guide#57]
**Is your feature request related to a problem? Please describe.**
Links, when placed in titles, have the same styling as when placed in normal text. It would be ideal for them to have the same font-family and color as other titles, but have the font-decoration set to "underline". 

**Describe the solution you'd like**
As described in the previous section. I found that the following css worked:
```css
#verification a {
  font-family: var(--pyc-theme-title-family);
  text-decoration: underline;
}
#verification a:not(:hover) {
  color: unset;
}
```
Before:

https://user-images.githubusercontent.com/71356958/159296276-99e67eae-51f2-4db9-92b5-d5d5992c0f11.mov

After (using the CSS above):

https://user-images.githubusercontent.com/71356958/159296100-854409e5-3bd2-4c3c-9386-6e3aad0f6fd3.mov

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by EmreTech** [comment]
This is a good idea, but there's a small problem. In CSS, we have to somehow set all link types that are also headers to have these properties. However, it's not like `<h2><a>` when everything is deployed, it's just `<a>`. So we have to somehow assign a class to these header links.

**Comment by MatteuSan** [comment]
Aight I have time to kill, imma do this

**Comment by BobDotCom** [comment]
> Aight I have time to kill, imma do this

It was actually recently improved by a change I made to the styling. Might not need further changes

Before:

![Screen Shot 2022-04-21 at 1 56 41 PM](https://user-images.githubusercontent.com/71356958/164533433-72863a99-18a8-45f8-a10d-0d5615917772.png)

After:

![Screen Shot 2022-04-21 at 1 56 13 PM](https://user-images.githubusercontent.com/71356958/164533363-391ba209-daab-4c0b-9369-71edf6c6ab65.png)

**Comment by MatteuSan** [comment]
Ah aight, so let's close this issue then

**Comment by MatteuSan** [comment]
because I found this fix lmao
```scss
.markdown {
  *[class*='anchor'] {
    > a:not([class='hash-link']) {
      font-family: sentro.token-get('title-family');
      text-decoration: underline;
    
      &:not(:hover) {
        color: unset;
      }
    }
  }
}
  ```
